"""PP16 symbol duration encoder and timing profile models.

PROVISIONAL / INFERRED WARNING:
Timing profiles defined in or generated by this module (including PrecIR prior art profiles)
are provisional/inferred and UNTESTED against physical Pricer ESL tags in this setup.
Physical carrier measurements from T005 are pending.
Do NOT claim verified tag or physical carrier compatibility until physical bench validation
is complete.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final

# Fixed safety and protocol bounds
MIN_CARRIER_HZ: Final[int] = 500_000
MAX_CARRIER_HZ: Final[int] = 2_000_000
MIN_DUTY_PERCENT: Final[int] = 10
MAX_DUTY_PERCENT: Final[int] = 60
MAX_FRAME_BYTES: Final[int] = 256
MAX_RMT_TICKS_PER_PHASE: Final[int] = 32_767
TICKS_PER_MICROSECOND: Final[int] = 10

# PrecIR prior art nibble total symbol durations in microseconds (0x0..0xF)
# Source: PrecIR commit b09951e2b3d2741e4ca08f929eafef849f6fc006
# (hardware/esl_blaster/FW02/Src/main.c; RE page https://www.furrtek.org/index.php?a=esl)
# GPL-3.0 license.
# Durations: 0x0=27, 0x1=51, 0x2=35, 0x3=43, 0x4=147, 0x5=123, 0x6=139, 0x7=131,
#            0x8=83, 0x9=59, 0xA=75, 0xB=67, 0xC=91, 0xD=115, 0xE=99, 0xF=107
PRECIR_NIBBLE_TOTAL_DURATIONS_US: Final[tuple[int, ...]] = (
    27,
    51,
    35,
    43,
    147,
    123,
    139,
    131,
    83,
    59,
    75,
    67,
    91,
    115,
    99,
    107,
)
PRECIR_BURST_US: Final[int] = 21
PRECIR_CARRIER_HZ: Final[int] = 1_250_000
PRECIR_PROVENANCE: Final[str] = (
    "PrecIR commit b09951e2b3d2741e4ca08f929eafef849f6fc006 (GPL-3.0) / "
    "Furrtek RE page https://www.furrtek.org/index.php?a=esl"
)


class PP16EncoderError(ValueError):
    """Raised when PP16 profile parameters or payload encoding fail validation."""


@dataclass(frozen=True, slots=True)
class SymbolTiming:
    """Microsecond burst and gap durations for one PP16 symbol."""

    burst_us: int
    gap_us: int

    @property
    def total_us(self) -> int:
        return self.burst_us + self.gap_us


@dataclass(frozen=True, slots=True)
class PP16TimingProfile:
    """Timing parameters for PP16 symbol waveform generation.

    Attributes:
        carrier_frequency_hz: Target IR carrier frequency (500 kHz .. 2 MHz).
        duty_percent: Carrier duty cycle (10% .. 60%).
        symbol_burst_us: Fixed burst duration in microseconds per data symbol.
        nibble_durations_us: Tuple of 16 total symbol durations (us) for nibbles 0..15.
        preamble_burst_us: Optional preamble pulse duration in microseconds (0 to disable).
        preamble_gap_us: Optional preamble space duration in microseconds.
        trailer_burst_us: Optional trailer pulse duration in microseconds (0 to disable).
        trailer_gap_us: Optional trailer space duration in microseconds.
        provenance: Reference source for profile timing parameters.
        is_provisional: Flag indicating profile is inferred/untested on target board.
    """

    carrier_frequency_hz: int = PRECIR_CARRIER_HZ
    duty_percent: int = 50
    symbol_burst_us: int = PRECIR_BURST_US
    nibble_durations_us: tuple[int, ...] = PRECIR_NIBBLE_TOTAL_DURATIONS_US
    preamble_burst_us: int = 0
    preamble_gap_us: int = 0
    trailer_burst_us: int = 0
    trailer_gap_us: int = 0
    provenance: str = PRECIR_PROVENANCE
    is_provisional: bool = True

    def validate(self) -> None:
        """Validate profile timing limits and raise PP16EncoderError if invalid."""
        if not (MIN_CARRIER_HZ <= self.carrier_frequency_hz <= MAX_CARRIER_HZ):
            raise PP16EncoderError(
                "carrier_frequency_hz "
                f"{self.carrier_frequency_hz} outside "
                f"[{MIN_CARRIER_HZ}, {MAX_CARRIER_HZ}]"
            )
        if not (MIN_DUTY_PERCENT <= self.duty_percent <= MAX_DUTY_PERCENT):
            raise PP16EncoderError(
                f"duty_percent {self.duty_percent} outside [{MIN_DUTY_PERCENT}, {MAX_DUTY_PERCENT}]"
            )
        if self.symbol_burst_us <= 0 or self.symbol_burst_us > 1000:
            raise PP16EncoderError(f"invalid symbol_burst_us {self.symbol_burst_us}")
        if len(self.nibble_durations_us) != 16:
            raise PP16EncoderError(
                "nibble_durations_us must contain exactly 16 values, "
                f"got {len(self.nibble_durations_us)}"
            )
        for idx, total_us in enumerate(self.nibble_durations_us):
            if total_us <= self.symbol_burst_us or total_us > 5000:
                raise PP16EncoderError(
                    f"nibble_durations_us[{idx}] value {total_us} us invalid "
                    f"for burst {self.symbol_burst_us} us"
                )
        if self.preamble_burst_us > 5000 or self.preamble_gap_us > 10000:
            raise PP16EncoderError(
                f"invalid preamble durations ({self.preamble_burst_us}, {self.preamble_gap_us})"
            )
        if self.trailer_burst_us > 5000 or self.trailer_gap_us > 10000:
            raise PP16EncoderError(
                f"invalid trailer durations ({self.trailer_burst_us}, {self.trailer_gap_us})"
            )

    def symbol_gap_us(self, nibble: int) -> int:
        """Return gap duration in microseconds for a 4-bit nibble (0..15)."""
        if not (0 <= nibble <= 15):
            raise PP16EncoderError(f"nibble {nibble} out of range 0..15")
        return self.nibble_durations_us[nibble] - self.symbol_burst_us

    def symbol_timing(self, nibble: int) -> SymbolTiming:
        """Return SymbolTiming (burst_us, gap_us) for a 4-bit nibble (0..15)."""
        return SymbolTiming(self.symbol_burst_us, self.symbol_gap_us(nibble))


def precir_pp16_profile() -> PP16TimingProfile:
    """Return PrecIR prior art PP16 profile with direct 16-entry nibble timing table."""
    profile = PP16TimingProfile()
    profile.validate()
    return profile


def provisional_pp16_profile() -> PP16TimingProfile:
    """Return default provisional PP16 profile with PrecIR prior art timing table."""
    return precir_pp16_profile()


def encode_pp16_symbols(
    payload: bytes | Sequence[int],
    profile: PP16TimingProfile | None = None,
) -> list[SymbolTiming]:
    """Encode payload bytes into PP16 symbol timings."""
    if profile is None:
        profile = provisional_pp16_profile()
    else:
        profile.validate()

    if len(payload) == 0:
        raise PP16EncoderError("payload must not be empty")
    if len(payload) > MAX_FRAME_BYTES:
        raise PP16EncoderError(
            f"payload size exceeds maximum allowed capacity ({MAX_FRAME_BYTES} bytes)"
        )

    symbols: list[SymbolTiming] = []

    if profile.preamble_burst_us > 0:
        symbols.append(SymbolTiming(profile.preamble_burst_us, profile.preamble_gap_us))

    # PrecIR's transmitter emits the low nibble before the high nibble.
    # The target ESL consumes each byte least-significant nibble first.
    for byte_val in payload:
        if not (0 <= byte_val <= 255):
            raise PP16EncoderError(f"byte value {byte_val} out of range 0..255")
        low_nibble = byte_val & 0x0F
        high_nibble = (byte_val >> 4) & 0x0F

        symbols.append(profile.symbol_timing(low_nibble))
        symbols.append(profile.symbol_timing(high_nibble))

    if profile.trailer_burst_us > 0:
        symbols.append(SymbolTiming(profile.trailer_burst_us, profile.trailer_gap_us))

    return symbols


def calculate_frame_duration_us(
    payload: bytes | Sequence[int],
    profile: PP16TimingProfile | None = None,
) -> int:
    """Calculate total microsecond duration for an encoded frame payload."""
    symbols = encode_pp16_symbols(payload, profile)
    return sum(s.total_us for s in symbols)


def encode_pp16_rmt_ticks(
    payload: bytes | Sequence[int],
    profile: PP16TimingProfile | None = None,
) -> list[tuple[int, int]]:
    """Encode payload into ESP32 RMT tick pairs (high_ticks, low_ticks)."""
    symbols = encode_pp16_symbols(payload, profile)
    rmt_items: list[tuple[int, int]] = []

    for s in symbols:
        high_ticks = s.burst_us * TICKS_PER_MICROSECOND
        low_ticks = s.gap_us * TICKS_PER_MICROSECOND

        if high_ticks > MAX_RMT_TICKS_PER_PHASE or low_ticks > MAX_RMT_TICKS_PER_PHASE:
            raise PP16EncoderError(
                f"RMT ticks for symbol burst or gap exceed max limit ({MAX_RMT_TICKS_PER_PHASE})"
            )

        rmt_items.append((high_ticks, low_ticks))

    return rmt_items
