"""Generate corrected PrecIR golden vectors and embedded orientation-test frames."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "pc" / "src"))

from eslbridge.precir import (
    BYTES_PER_FRAME,
    PricerPlid,
    derive_pricer_plid,
    make_mcu_frame,
    make_raw_frame,
    pad_image_payload,
)

BARCODE = "N4163114582613272"
PROFILE_REVISION = "T008C-r1"
VECTOR_DIR = ROOT / "tests" / "vectors"
ORIENTATION_SOURCE = ROOT / "firmware" / "src" / "orientation_test.cpp"
RAW_IMAGE_PAYLOAD = bytes.fromhex("f00ff00ff00ff00ff00ff00ff00ff00f")


def make_image_data_bodies(payload: bytes) -> list[bytes]:
    padded_payload = pad_image_payload(payload)
    return [
        packet_index.to_bytes(2, "big") + padded_payload[offset : offset + BYTES_PER_FRAME]
        for packet_index, offset in enumerate(range(0, len(padded_payload), BYTES_PER_FRAME))
    ]


def cpp_bytes(frame: bytes) -> str:
    rows = []
    for offset in range(0, len(frame), 13):
        values = ", ".join(f"0x{value:02X}" for value in frame[offset : offset + 13])
        rows.append(f"    {values},")
    return "\n".join(rows)


def make_vectors() -> tuple[PricerPlid, dict[str, bytes], dict[str, bytes]]:
    plid = derive_pricer_plid(BARCODE)
    assert plid == PricerPlid(internal=b"\x3f\xb7\xb3\x02", wire=b"\x02\xb3\xb7\x3f")

    padded_image = pad_image_payload(RAW_IMAGE_PAYLOAD)
    image_data_bodies = make_image_data_bodies(RAW_IMAGE_PAYLOAD)
    assert len(image_data_bodies) == 1

    bodies = {
        "wake.bin": bytes.fromhex("01000000" + "01" * 22),
        "params-8x8-color.bin": len(padded_image).to_bytes(2, "big")
        + bytes.fromhex("0000010008000800000000000088000000000000"),
        "data-8x8-color.bin": image_data_bodies[0],
        "refresh.bin": b"\x00" * 22,
    }
    commands = {
        "wake.bin": 0x17,
        "params-8x8-color.bin": 0x05,
        "data-8x8-color.bin": 0x20,
        "refresh.bin": 0x01,
    }
    frames = {
        name: (
            make_raw_frame(plid, commands[name], body)
            if name == "wake.bin"
            else make_mcu_frame(plid, commands[name], body)
        )
        for name, body in bodies.items()
    }
    return plid, bodies, frames


def write_manifest(
    plid: PricerPlid, bodies: dict[str, bytes], frames: dict[str, bytes]
) -> None:
    commands = {
        "wake.bin": 0x17,
        "params-8x8-color.bin": 0x05,
        "data-8x8-color.bin": 0x20,
        "refresh.bin": 0x01,
    }
    manifest = {
        "target": {
            "marking": "#19523-01",
            "barcode": BARCODE,
            "profile": "Pricer graphic medium 208x112 black/white/red",
            "plid_internal_order": plid.internal.hex(),
            "plid_formula_result": plid.wire.hex(),
            "raw_frame_plid_order": plid.wire.hex(),
            "modulation": 16,
        },
        "profile_revision": PROFILE_REVISION,
        "transmission": {
            "wake_repeats": 400,
            "wake_repeat_gap_us": 2000,
            "image_repeats": 1,
            "image_repeat_gap_us": 0,
        },
        "vectors": [
            {
                "name": name,
                "command": f"0x{commands[name]:02x}",
                "frame_length": len(frames[name]),
                "payload_hex": bodies[name].hex(),
                "finalized_hex": frames[name].hex(),
                "crc16_le_hex": frames[name][-2:].hex(),
            }
            for name in bodies
        ],
    }
    (VECTOR_DIR / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )


def write_orientation_source(frames: dict[str, bytes]) -> None:
    source = f"""#include "orientation_test.hpp"

#include "ir_transmitter.hpp"

// Generated by scripts/generate_vectors.py; do not edit the frame arrays manually.
namespace eslbridge {{
namespace {{

constexpr std::uint8_t kWakeFrame[] = {{
{cpp_bytes(frames["wake.bin"])}
}};

constexpr std::uint8_t kParamsFrame[] = {{
{cpp_bytes(frames["params-8x8-color.bin"])}
}};

constexpr std::uint8_t kDataFrame[] = {{
{cpp_bytes(frames["data-8x8-color.bin"])}
}};

constexpr std::uint8_t kRefreshFrame[] = {{
{cpp_bytes(frames["refresh.bin"])}
}};

constexpr OrientationTestPlan kPlan = {{
    std::array<OrientationTestFrame, 4>{{{{
        {{kWakeFrame, sizeof(kWakeFrame), 400, 2'000}},
        {{kParamsFrame, sizeof(kParamsFrame), 1, 0}},
        {{kDataFrame, sizeof(kDataFrame), 1, 0}},
        {{kRefreshFrame, sizeof(kRefreshFrame), 1, 0}},
    }}}},
}};
}}  // namespace

const OrientationTestPlan& orientation_test_plan(const OrientationTest /*test*/) {{
    return kPlan;
}}

const char* orientation_test_name(const OrientationTest test) {{
    switch (test) {{
        case OrientationTest::kOne:
            return "TEST-1";
        case OrientationTest::kTwo:
            return "TEST-2";
        case OrientationTest::kThree:
            return "TEST-3";
        case OrientationTest::kFour:
            return "TEST-4";
        default:
            return "NONE";
    }}
}}

protocol::Status run_orientation_test(IrTransmitter& transmitter, const OrientationTest test) {{
    if (test == OrientationTest::kNone) {{
        return protocol::Status::kInvalidArgument;
    }}

    for (const auto& frame : orientation_test_plan(test).frames) {{
        const auto status = transmitter.send_pricer_frame(
            16, frame.repeats, frame.inter_repeat_gap_us, frame.data, frame.length);
        if (status != protocol::Status::kOk) {{
            return status;
        }}
    }}
    return protocol::Status::kOk;
}}

}}  // namespace eslbridge
"""
    ORIENTATION_SOURCE.write_text(source, encoding="utf-8")


def main() -> None:
    plid, bodies, frames = make_vectors()
    VECTOR_DIR.mkdir(parents=True, exist_ok=True)
    for name, frame in frames.items():
        (VECTOR_DIR / name).write_bytes(frame)
    write_manifest(plid, bodies, frames)
    write_orientation_source(frames)


if __name__ == "__main__":
    main()
