[platformio]
default_envs = m5stack-cardputer-adv

[env:m5stack-cardputer-adv]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DPROJECT_VERSION=\"0.1.0\"

lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer.git#f1392858b9994c3547120e602a57d3553d16ab01

check_tool = cppcheck
check_flags =
    cppcheck: --enable=warning,style,performance,portability
